# Actividad 2

In [15]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score

#Importe de Datos
df = pd.read_csv("./SalsberryRealty.csv")
df.head()

   Cost  Temp  Insul  Age  Garage
0   250    35      3    6       0
1   360    29      4   10       1
2   165    36      7    3       0
3    43    60      6    9       0
4    92    65      5    6       0

## Determinar las variables independientes

In [16]:
X = df[['Temp', 'Insul', 'Age']]
X

    Temp  Insul  Age
0     35      3    6
1     29      4   10
2     36      7    3
3     60      6    9
4     65      5    6
5     30      5    5
6     10      6    7
7      7     10   10
8     21      9   11
9     55      2    5
10    54     12    4
11    48      5    1
12    20      5   15
13    39      4    7
14    60      8    6
15    20      5    8
16    58      7    3
17    40      8   11
18    27      9    8
19    30      7    5

## Determinar la variables dependiente

In [17]:
y =df[['Cost']]
y

    Cost
0    250
1    360
2    165
3     43
4     92
5    200
6    355
7    290
8    230
9    120
10    73
11   205
12   400
13   320
14    72
15   272
16    94
17   190
18   235
19   139

## Ajustar el modelo para encontrar el modelo de regresion multiple

In [18]:
model = LinearRegression()
model.fit(X,y)
y_pred = model.predict(X)

mse = mean_squared_error(y,y_pred)
r2 = r2_score(y,y_pred)

## Obtener el valor de interseccion

In [19]:
model.intercept_

array([427.19380332])

In [20]:
print('Coefcientes: ', model.coef_)
print('Error cuadratico de la media', mse)
print('Variaza: ', r2)

Coefcientes:  [[ -4.58266263 -14.83086269   6.10103206]]
Error cuadratico de la media 2084.7638583181533
Variaza:  0.804170066487035

## 4. Estimar para 30, aislamiento 5", antiguedad 10 años

In [21]:
Y = model.predict([[30, 5, 10]])
print("El costo de calefaccion es: ", Y)

El costo de calefaccion es:  [[276.56993172]]

c:\Users\marco\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(